ALTER TABLE "FlightOrder"
  ADD COLUMN "customerCurrency" TEXT NOT NULL DEFAULT 'ETB',
  ADD COLUMN "exchangeRate" DOUBLE PRECISION,
  ADD COLUMN "baseFare" DOUBLE PRECISION,
  ADD COLUMN "taxes" DOUBLE PRECISION,
  ADD COLUMN "seatAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "ancillaryAmount" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN "selectedSeats" JSONB,
  ADD COLUMN "selectedServices" JSONB,
  ADD COLUMN "eticketNumber" TEXT;
