CREATE TYPE "PaymentStatus" AS ENUM ('PAID', 'UNPAID', 'REFUNDED');
ALTER TABLE "ServiceRequest" ADD COLUMN "paymentStatus" "PaymentStatus" NOT NULL DEFAULT 'UNPAID', ADD COLUMN "paymentId" TEXT, ADD COLUMN "amount" DOUBLE PRECISION, ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'ETB', ADD COLUMN "paidAt" TIMESTAMP(3);
