import type { Metadata } from "next";
import { ResourcePage, Section } from "@/components/site/resource-page";
export const metadata: Metadata = {
  title: "Umrah Guide 2026 — Requirements, Rituals & Packages from Ethiopia",
  description:
    "Complete Umrah guide for Ethiopian travelers: visa requirements, ihram, Tawaf and Sa'i step by step, packing and health tips — plus the best 3, 5 and 10-day Umrah packages from Addis Ababa with IATA-accredited TOGT Tour & Travel.",
  keywords: ["umrah guide", "umrah requirements Ethiopia", "umrah visa from Ethiopia", "how to perform umrah", "umrah packages Addis Ababa", "best umrah travel Ethiopia"],
};
export default function UmrahGuidePage() { return <ResourcePage title="Umrah Guide" subtitle="A complete step-by-step guide for preparing your sacred journey."><Section title="1. What is Umrah?"><p>Umrah is a voluntary pilgrimage to Makkah that can be performed at any time of the year. Preparation, sincerity, and respect for the sacred places are central to the journey.</p></Section><Section title="2. Requirements and Visa"><p>Carry a valid passport, approved visa, recent photographs, confirmed accommodation and travel details, and any required vaccination documentation. Requirements can change, so confirm the latest rules before travel.</p></Section><Section title="3. Ihram and Intention"><p>Enter ihram at the appropriate miqat, make the intention for Umrah, and observe the restrictions of ihram. Ask a qualified guide if you are unsure about any step.</p></Section><Section title="4. Tawaf and Sa&apos;i"><p>Complete seven circuits of Tawaf around the Kaaba, then perform Sa&apos;i between Safa and Marwah. Finish by shaving or shortening the hair to complete Umrah.</p></Section><Section title="5. What to Pack and Health Tips"><p>Pack comfortable footwear, unscented personal items, medication, hydration supplies, copies of documents, and modest practical clothing. Rest regularly and follow local health guidance.</p></Section><Section title="6. Frequently Asked Questions"><p>TOGT guides can help with flights, visa processing, accommodation, transport, and pre-departure preparation. Contact us early so your documents and itinerary can be reviewed carefully.</p></Section></ResourcePage>; }
