"use client";

import { useEffect, useMemo, useState } from "react";
import { Database, KeyRound, LockKeyhole, RefreshCw, ShieldCheck, Terminal, Wrench, XCircle } from "lucide-react";
import { ApiError } from "@/lib/api/client";
import { deleteSystemProvider, getSystemAuditLogs, getSystemBackups, getSystemHealth, getSystemLogs, getSystemMaintenance, getSystemMetrics, getSystemMigrations, getSystemProviders, getSystemVersion, requestSystemBackup, saveSystemProvider, setSystemMaintenance, testSystemProvider, type ProviderStatus, type SystemHealth } from "@/lib/api/system";

const tabs = ["Overview", "Providers", "Database", "Backups", "Logs", "Security", "Maintenance"] as const;
const providerLabels: Record<string, string> = { OPENROUTER: "OpenRouter", OPENAI: "OpenAI", GEMINI: "Google Gemini", DUFFEL: "Duffel", CHAPA: "Chapa", RESEND: "Resend", SMS_ETHIOPIA: "SMSEthiopia", MAPBOX: "Mapbox", R2: "Cloudflare R2", TELEGRAM: "Telegram", FIREBASE: "Firebase / FCM" };
const fmtBytes = (n?: number) => n == null ? "—" : `${(n / 1024 / 1024 / 1024).toFixed(1)} GB`;
const fmtUptime = (n: number) => `${Math.floor(n / 86400)}d ${Math.floor(n / 3600) % 24}h ${Math.floor(n / 60) % 60}m`;

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-slate-200 bg-white p-5 shadow-sm ${className}`}>{children}</section>; }
function Status({ ok, children }: { ok: boolean; children: React.ReactNode }) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-bold ${ok ? "bg-emerald-50 text-emerald-700" : "bg-rose-50 text-rose-700"}`}><span className={`h-2 w-2 rounded-full ${ok ? "bg-emerald-500" : "bg-rose-500"}`} />{children}</span>; }

export function SystemDashboard() {
  const [tab, setTab] = useState<(typeof tabs)[number]>("Overview");
  const [health, setHealth] = useState<SystemHealth | null>(null);
  const [metrics, setMetrics] = useState<{ activeUsers: number; users: number; activeRequests: number; pendingBackups: number; requestRate: number | null; responseTimeMs: number | null; note: string } | null>(null);
  const [providers, setProviders] = useState<ProviderStatus[]>([]);
  const [backups, setBackups] = useState<Array<{ id: string; status: string; destination: string; startedAt: string; completedAt?: string }>>([]);
  const [logs, setLogs] = useState<Array<{ id: number; level: string; message: string }>>([]);
  const [audit, setAudit] = useState<Array<{ id: string; action: string; outcome: string; target?: string; createdAt: string }>>([]);
  const [maintenance, setMaintenance] = useState<{ enabled: boolean; message: string } | null>(null);
  const [migrations, setMigrations] = useState<{ applied: number; runnerConfigured: boolean } | null>(null);
  const [version, setVersion] = useState<{ version: string; commit: string; node: string; environment: string } | null>(null);
  const [selectedProvider, setSelectedProvider] = useState<string | null>(null);
  const [secret, setSecret] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");

  const load = async () => {
    setError("");
    try {
      const [h, m, p, b, l, a, ma, mi, v] = await Promise.all([getSystemHealth(), getSystemMetrics(), getSystemProviders(), getSystemBackups(), getSystemLogs(), getSystemAuditLogs(), getSystemMaintenance(), getSystemMigrations(), getSystemVersion()]);
      setHealth(h); setMetrics(m); setProviders(p); setBackups(b); setLogs(l.entries); setAudit(a); setMaintenance(ma); setMigrations(mi); setVersion(v);
    } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to load system data"); }
  };
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => window.clearInterval(timer); }, []);
  const alerts = useMemo(() => [health?.database !== "UP" ? "Database is unavailable" : null, health && health.memory.usedPercent > 85 ? "Memory usage is high" : null, maintenance?.enabled ? "Maintenance mode is enabled" : null].filter(Boolean) as string[], [health, maintenance]);
  const action = async (fn: () => Promise<unknown>) => { setBusy(true); setError(""); try { await fn(); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : "Operation failed"); } finally { setBusy(false); } };

  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-togt-orange">Operations center</p><h1 className="mt-1 text-3xl font-black text-togt-navy">System Control</h1><p className="mt-1 text-sm text-slate-500">TECH-only infrastructure, security, and service operations.</p></div><button onClick={() => void load()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-togt-blue px-4 py-2.5 text-sm font-bold text-white"><RefreshCw className="h-4 w-4" />Refresh</button></div>
    {error && <div className="flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700"><XCircle className="h-4 w-4" />{error}</div>}
    {alerts.length > 0 && <div className="grid gap-2 md:grid-cols-3">{alerts.map((alert) => <div key={alert} className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-semibold text-amber-800">{alert}</div>)}</div>}
    <div className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-2">{tabs.map((item) => <button key={item} onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-bold ${tab === item ? "bg-togt-navy text-white" : "text-slate-500 hover:bg-slate-100"}`}>{item}</button>)}</div>
    {tab === "Overview" && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card><p className="text-xs font-bold uppercase text-slate-400">System</p><p className="mt-2 text-xl font-black text-togt-navy">{health?.status ?? "CHECKING"}</p><p className="text-xs text-slate-500">{health?.host ?? "—"}</p></Card><Card><p className="text-xs font-bold uppercase text-slate-400">Memory</p><p className="mt-2 text-xl font-black text-togt-navy">{health?.memory.usedPercent ?? "—"}%</p><p className="text-xs text-slate-500">{fmtBytes(health?.memory.usedBytes)} / {fmtBytes(health?.memory.totalBytes)}</p></Card><Card><p className="text-xs font-bold uppercase text-slate-400">Active users</p><p className="mt-2 text-xl font-black text-togt-navy">{metrics?.activeUsers ?? "—"}</p><p className="text-xs text-slate-500">{metrics?.users ?? "—"} total accounts</p></Card><Card><p className="text-xs font-bold uppercase text-slate-400">Uptime</p><p className="mt-2 text-xl font-black text-togt-navy">{health ? fmtUptime(health.uptimeSeconds) : "—"}</p><p className="text-xs text-slate-500">Node {health?.node ?? "—"}</p></Card></div><Card><div className="mb-4 flex items-center justify-between"><h2 className="font-black text-togt-navy">Core services</h2><Status ok={health?.status === "UP"}>API {health?.status ?? "CHECKING"}</Status></div><div className="grid gap-3 sm:grid-cols-4"><Status ok={health?.database === "UP"}>PostgreSQL {health?.database ?? "—"}</Status><Status ok={health?.valkey === "CONFIGURED"}>Valkey {health?.valkey ?? "—"}</Status><Status ok={!!health}>Web reachable via dashboard</Status><Status ok={false}>Host runner unavailable</Status></div></Card><Card><h2 className="mb-3 font-black text-togt-navy">Operational snapshot</h2><div className="grid gap-3 text-sm sm:grid-cols-3"><p>Active requests: <b>{metrics?.activeRequests ?? "—"}</b></p><p>Pending backups: <b>{metrics?.pendingBackups ?? "—"}</b></p><p>Request rate: <b>{metrics?.requestRate ?? "Not collected"}</b></p></div></Card></div>}
    {tab === "Providers" && <Card><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-togt-navy">Provider credentials</h2><p className="text-xs text-slate-500">Secrets are write-only and never returned by the API.</p></div><LockKeyhole className="h-5 w-5 text-togt-orange" /></div><div className="grid gap-3 md:grid-cols-2">{providers.map((item) => <div key={item.provider} className="flex items-center justify-between rounded-xl border border-slate-200 p-4"><div><p className="font-bold text-togt-navy">{providerLabels[item.provider] ?? item.provider}</p><div className="mt-1 flex gap-2"><Status ok={item.configured}>{item.configured ? "SET" : "MISSING"}</Status>{item.lastTestStatus && <Status ok={item.lastTestStatus === "PASS"}>{item.lastTestStatus}</Status>}</div></div><div className="flex gap-2"><button disabled={!item.configured || busy} onClick={() => void action(() => testSystemProvider(item.provider))} className="rounded-lg border px-3 py-2 text-xs font-bold">Test</button><button onClick={() => { setSelectedProvider(item.provider); setSecret(""); }} className="rounded-lg bg-togt-blue px-3 py-2 text-xs font-bold text-white">{item.configured ? "Rotate" : "Add"}</button>{item.configured && <button onClick={() => void action(() => deleteSystemProvider(item.provider))} className="rounded-lg border border-rose-200 px-3 py-2 text-xs font-bold text-rose-600">Delete</button>}</div></div>)}</div></Card>}
    {tab === "Database" && <div className="grid gap-4 md:grid-cols-2"><Card><Database className="mb-3 h-6 w-6 text-togt-blue" /><h2 className="font-black text-togt-navy">Database status</h2><p className="mt-2 text-sm">Connection: <b>{health?.database ?? "—"}</b></p><p className="text-sm">Applied migrations: <b>{migrations?.applied ?? "—"}</b></p><p className="text-sm">Runner: <b>{migrations?.runnerConfigured ? "Configured" : "Not configured"}</b></p></Card><Card><Terminal className="mb-3 h-6 w-6 text-togt-orange" /><h2 className="font-black text-togt-navy">Migration control</h2><p className="mt-2 text-sm text-slate-500">Migration execution is fail-closed until the restricted host runner is installed.</p><button disabled className="mt-4 rounded-lg bg-slate-200 px-3 py-2 text-xs font-bold text-slate-500">Runner unavailable</button></Card></div>}
    {tab === "Backups" && <Card><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-togt-navy">Full backups</h2><p className="text-xs text-slate-500">Database and uploaded files to private R2.</p></div><button disabled={busy} onClick={() => void action(requestSystemBackup)} className="rounded-lg bg-togt-orange px-3 py-2 text-xs font-bold text-white">Backup now</button></div>{backups.length ? <div className="space-y-2">{backups.map((backup) => <div key={backup.id} className="flex justify-between rounded-lg bg-slate-50 p-3 text-sm"><span>{new Date(backup.startedAt).toLocaleString()}</span><b>{backup.status}</b></div>)}</div> : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No backups recorded. Configure the restricted host runner before creating production backups.</p>}</Card>}
    {tab === "Logs" && <Card><div className="mb-4 flex items-center gap-2"><Terminal className="h-5 w-5 text-togt-blue" /><h2 className="font-black text-togt-navy">Redacted system logs</h2></div>{logs.length ? <div className="max-h-[32rem] overflow-auto rounded-xl bg-slate-950 p-4 font-mono text-xs text-slate-200">{logs.map((log) => <p key={log.id} className={log.level === "ERROR" ? "text-rose-300" : log.level === "WARN" ? "text-amber-300" : ""}>[{log.level}] {log.message}</p>)}</div> : <p className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No allowlisted log source configured.</p>}</Card>}
    {tab === "Security" && <div className="space-y-4"><Card><ShieldCheck className="mb-3 h-6 w-6 text-emerald-600" /><h2 className="font-black text-togt-navy">Audit trail</h2><div className="mt-3 space-y-2">{audit.length ? audit.map((item) => <div key={item.id} className="flex justify-between border-b py-2 text-sm"><span>{item.action} {item.target ?? ""}</span><span className="text-slate-500">{item.outcome} · {new Date(item.createdAt).toLocaleString()}</span></div>) : <p className="text-sm text-slate-500">No operations recorded.</p>}</div></Card><Card><KeyRound className="mb-3 h-6 w-6 text-togt-orange" /><h2 className="font-black text-togt-navy">Build and runtime</h2><p className="text-sm">Version: {version?.version ?? "—"}</p><p className="text-sm">Commit: {version?.commit ?? "—"}</p><p className="text-sm">Environment: {version?.environment ?? "—"}</p></Card></div>}
    {tab === "Maintenance" && <Card><Wrench className="mb-3 h-6 w-6 text-togt-orange" /><h2 className="font-black text-togt-navy">Maintenance mode</h2><p className="mt-1 text-sm text-slate-500">The API currently stores the state. A request gate must be enabled before this affects public traffic.</p><label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={maintenance?.enabled ?? false} onChange={(event) => setMaintenance((current) => ({ enabled: event.target.checked, message: current?.message ?? "TOGT is temporarily unavailable for maintenance." }))} />Enabled</label><textarea value={maintenance?.message ?? "TOGT is temporarily unavailable for maintenance."} onChange={(event) => setMaintenance((current) => ({ enabled: current?.enabled ?? false, message: event.target.value }))} className="mt-3 min-h-24 w-full rounded-xl border p-3 text-sm" /><button disabled={busy} onClick={() => void action(() => setSystemMaintenance(maintenance?.enabled ?? false, maintenance?.message ?? "TOGT is temporarily unavailable for maintenance."))} className="mt-3 rounded-lg bg-togt-blue px-4 py-2 text-sm font-bold text-white">Save maintenance settings</button></Card>}
    {selectedProvider && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="font-black text-togt-navy">Configure {providerLabels[selectedProvider] ?? selectedProvider}</h2><button onClick={() => setSelectedProvider(null)}><XCircle className="h-5 w-5" /></button></div><p className="mt-2 text-xs text-slate-500">The value is encrypted at rest and cannot be viewed after saving.</p><input autoFocus type="password" value={secret} onChange={(event) => setSecret(event.target.value)} placeholder="Paste secret value" className="mt-4 w-full rounded-xl border p-3 text-sm" /><div className="mt-4 flex justify-end gap-2"><button onClick={() => setSelectedProvider(null)} className="rounded-lg border px-4 py-2 text-sm font-bold">Cancel</button><button disabled={!secret || busy} onClick={() => void action(async () => { await saveSystemProvider(selectedProvider, secret, true); setSelectedProvider(null); })} className="rounded-lg bg-togt-orange px-4 py-2 text-sm font-bold text-white">Save encrypted key</button></div></div></div>}
  </div>;
}
