"use client";

import { useState } from "react";
import { Bell, BellRing, Box, CalendarDays, Check, ChevronRight, Clock3, Compass, House, MapPinned, MessageCircle, Package as PackageIcon, Phone, Plane, Search, UserRound } from "lucide-react";
import { useAuth } from "@/hooks/useAuth";
import { useDisplayPackages } from "@/hooks/usePackages";
import { streamChatbot } from "@/lib/api/chatbot";
import type { DisplayPackage } from "@/lib/api/packages";

type Tab = "home" | "packages" | "umrah" | "chat" | "profile";

const tabs: Array<{ id: Tab; label: string; icon: typeof House }> = [
  { id: "home", label: "Home", icon: House }, { id: "packages", label: "Packages", icon: Box }, { id: "umrah", label: "Umrah", icon: PackageIcon }, { id: "chat", label: "Chat", icon: MessageCircle }, { id: "profile", label: "Profile", icon: UserRound },
];

export function NativeAppShell() {
  const [tab, setTab] = useState<Tab>("home");
  const { user, logout } = useAuth();
  return <div className="native-shell min-h-screen bg-slate-50 pb-24 text-togt-navy">{tab === "home" && <NativeHome onTab={setTab} />}{tab === "packages" && <NativePackages />}{tab === "umrah" && <NativeUmrah onTab={setTab} />}{tab === "chat" && <NativeChat />}{tab === "profile" && <NativeProfile user={user} logout={logout} onTab={setTab} />}{<nav className="fixed inset-x-0 bottom-0 z-50 flex justify-around border-t border-slate-200 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] pt-2 shadow-[0_-8px_25px_rgba(18,57,79,0.08)] backdrop-blur">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={`flex min-w-14 flex-col items-center gap-1 rounded-xl px-3 py-2 text-[11px] font-semibold transition-all duration-200 ${tab === id ? "text-togt-orange" : "text-slate-400"}`}><Icon className={`h-5 w-5 transition-transform duration-200 ${tab === id ? "scale-110 text-togt-orange" : ""}`} />{label}</button>)}</nav>}</div>;
}

function NativeHeader({ title, action }: { title: string; action?: React.ReactNode }) { return <header className="sticky top-0 z-30 flex items-center justify-between bg-slate-50/95 px-5 pb-3 pt-[calc(env(safe-area-inset-top)+1rem)] backdrop-blur"><h1 className="text-2xl font-extrabold tracking-tight">{title}</h1>{action}</header>; }

function NativeHome({ onTab }: { onTab: (tab: Tab) => void }) { const { data: packages } = useDisplayPackages(); const featured = packages?.slice(0, 5) ?? []; return <main><NativeHeader title="TOGT" action={<Bell className="h-5 w-5 text-togt-blue" />} /><div className="px-5"><div className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 shadow-sm"><Search className="h-5 w-5 text-slate-400" /><span className="text-sm text-slate-400">Where are you going?</span></div><section className="mt-5 overflow-hidden rounded-3xl bg-gradient-to-br from-togt-navy to-togt-blue p-6 text-white shadow-xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-togt-orange">Travel with confidence</p><h2 className="mt-3 text-3xl font-extrabold">Your journey,<br /><span className="text-togt-orange">managed beautifully.</span></h2><p className="mt-3 text-sm text-white/70">Tickets, Umrah, tours, visas, and support in one place.</p><button onClick={() => onTab("packages")} className="mt-5 rounded-xl bg-togt-orange px-5 py-3 text-sm font-bold text-white">Explore packages</button></section><section className="mt-6"><h2 className="mb-3 text-lg font-bold">Quick actions</h2><div className="grid grid-cols-4 gap-2">{[["Tickets", Plane, "#flight-booking"], ["Umrah", PackageIcon, "umrah"], ["Tours", CalendarDays, "packages"], ["Visa", Check, "packages"]].map(([label, Icon, target]) => <button key={label as string} onClick={() => onTab(target === "umrah" ? "umrah" : target === "packages" ? "packages" : "home")} className="flex flex-col items-center gap-2 rounded-2xl bg-white p-3 text-xs font-semibold shadow-sm"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-togt-blue/10 text-togt-blue"><Icon className="h-5 w-5" /></span>{label as string}</button>)}</div></section><section className="mt-7"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">Featured packages</h2><button onClick={() => onTab("packages")} className="text-xs font-bold text-togt-orange">View all</button></div><div className="flex snap-x gap-3 overflow-x-auto pb-2">{featured.map((pkg) => <NativePackageCard key={pkg.id} pkg={pkg} compact onBook={() => onTab("packages")} />)}</div></section><section className="mt-6 rounded-2xl bg-white p-4 shadow-sm"><h2 className="font-bold">Need help?</h2><div className="mt-3 flex gap-2"><a href="tel:+251997979741" className="flex flex-1 items-center justify-center gap-1 rounded-xl bg-togt-orange py-3 text-xs font-bold text-white"><Phone className="h-4 w-4" />Call</a><button onClick={() => onTab("chat")} className="flex flex-1 items-center justify-center gap-1 rounded-xl bg-togt-blue py-3 text-xs font-bold text-white"><MessageCircle className="h-4 w-4" />Chat</button></div></section></div></main>; }

function NativePackages() { const [search, setSearch] = useState(""); const [category, setCategory] = useState("ALL"); const { data: packages, isLoading, refetch } = useDisplayPackages(); const filtered = (packages ?? []).filter((pkg) => (!search || `${pkg.title} ${pkg.fullDescription}`.toLowerCase().includes(search.toLowerCase())) && (category === "ALL" || pkg.type.toUpperCase().includes(category))); return <main><NativeHeader title="Packages" action={<button onClick={() => void refetch()}><Bell className="h-5 w-5 text-togt-blue" /></button>} /><div className="px-5"><div className="flex items-center gap-2 rounded-2xl bg-white px-4 py-3 shadow-sm"><Search className="h-5 w-5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search packages" className="w-full bg-transparent text-sm outline-none" /></div><div className="mt-4 flex gap-2 overflow-x-auto pb-2">{["ALL", "UMRAH", "DOMESTIC", "TOURIST", "FOREIGN"].map((value) => <button key={value} onClick={() => setCategory(value)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${category === value ? "bg-togt-orange text-white" : "bg-white text-slate-500"}`}>{value === "ALL" ? "All" : value}</button>)}</div><div className="mt-3 space-y-4">{isLoading && <p className="py-8 text-center text-sm text-slate-400">Loading packages...</p>}{filtered.map((pkg) => <NativePackageCard key={pkg.id} pkg={pkg} onBook={() => window.alert("Open the booking form from the website to complete this request.")} />)}</div></div></main>; }

function NativePackageCard({ pkg, compact = false, onBook }: { pkg: DisplayPackage; compact?: boolean; onBook: () => void }) { return <article className={`${compact ? "w-64 shrink-0 snap-start" : ""} overflow-hidden rounded-2xl bg-white shadow-sm`}><img src={pkg.image || "/images/packages/umrah-economy.jpg"} alt={pkg.title} className={`${compact ? "h-28" : "h-40"} w-full object-cover`} /><div className="p-4"><h3 className="font-bold">{pkg.title}</h3><p className="mt-1 text-sm font-bold text-togt-orange">{pkg.price ? `${pkg.price.toLocaleString()} ${pkg.currency ?? "ETB"}` : "Custom pricing"} <span className="font-normal text-slate-400">· {pkg.durationDays ? `${pkg.durationDays} days` : "Flexible"}</span></p>{!compact && <p className="mt-2 line-clamp-2 text-xs text-slate-500">{pkg.fullDescription}</p>}<button onClick={onBook} className="mt-3 w-full rounded-xl bg-togt-blue py-2.5 text-xs font-bold text-white">Book Now</button></div></article>; }

function NativeUmrah({ onTab }: { onTab: (tab: Tab) => void }) {
  const tools = [
    { label: "Qibla Locator", icon: Compass, tone: "bg-blue-50 text-blue-600" },
    { label: "Prayer Times", icon: Clock3, tone: "bg-violet-50 text-violet-600" },
    { label: "Azan Alarm", icon: BellRing, tone: "bg-amber-50 text-amber-600" },
    { label: "Group Tracking", icon: MapPinned, tone: "bg-emerald-50 text-emerald-600" },
  ];

  return <main><NativeHeader title="Umrah Center" /><div className="px-5"><div className="grid grid-cols-2 gap-3">{tools.map(({ label, icon: Icon, tone }) => <button key={label} className="group rounded-2xl border border-slate-100 bg-white p-5 text-left shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"><span className={`flex h-12 w-12 items-center justify-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></span><p className="mt-3 text-sm font-bold text-slate-800">{label}</p></button>)}</div><section className="mt-6 rounded-2xl bg-togt-navy p-5 text-white shadow-lg"><p className="text-xs uppercase tracking-widest text-togt-orange">Journey guide</p><h2 className="mt-2 text-xl font-bold">Prepare for Umrah</h2><p className="mt-2 text-sm text-white/70">Learn about ihram, Tawaf, Sa&apos;i, documents, health, and packing.</p><button onClick={() => onTab("packages")} className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-togt-orange transition-transform duration-200 hover:translate-x-1">View Umrah packages <ChevronRight className="h-4 w-4" /></button></section></div></main>;
}

function NativeChat() { const [draft, setDraft] = useState(""); const [messages, setMessages] = useState<Array<{ from: "bot" | "user"; text: string }>>([{ from: "bot", text: "Hi! I&apos;m Ahmed from TOGT. How can I help with your journey?" }]); const [typing, setTyping] = useState(false); const [conversationId] = useState(() => `native-${Date.now()}`); const send = async (event: React.FormEvent) => { event.preventDefault(); const text = draft.trim(); if (!text || typing) return; setDraft(""); setMessages((current) => [...current, { from: "user", text }, { from: "bot", text: "" }]); setTyping(true); try { await streamChatbot(text, conversationId, (chunk) => setMessages((current) => { const next = [...current]; next[next.length - 1].text += chunk; return next; })); } catch { setMessages((current) => [...current, { from: "bot", text: "Please call TOGT support at +251 99 797 9741." }]); } finally { setTyping(false); } }; return <main className="flex min-h-screen flex-col"><NativeHeader title="Chat" /><div className="flex-1 space-y-3 overflow-y-auto px-5">{messages.map((message, index) => <div key={index} className={`max-w-[85%] rounded-2xl p-3 text-sm ${message.from === "user" ? "ml-auto bg-togt-blue text-white" : "bg-white shadow-sm"}`}>{message.text}</div>)}{typing && <p className="text-xs text-slate-400">Ahmed is typing...</p>}</div><form onSubmit={send} className="sticky bottom-20 mx-5 mb-3 flex gap-2 rounded-2xl bg-white p-2 shadow-lg"><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Ask about travel..." className="min-w-0 flex-1 px-2 text-sm outline-none" /><button className="rounded-xl bg-togt-orange p-3 text-white"><MessageCircle className="h-4 w-4" /></button></form></main>; }

function NativeProfile({ user, logout, onTab }: { user: ReturnType<typeof useAuth>["user"]; logout: () => Promise<void>; onTab: (tab: Tab) => void }) { return <main><NativeHeader title="Profile" /><div className="px-5"><div className="flex items-center gap-4 rounded-2xl bg-white p-5 shadow-sm"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-togt-blue text-xl font-bold text-white">{user?.fullName?.slice(0, 2).toUpperCase() ?? "?"}</span><div><h2 className="font-bold">{user?.fullName ?? "Guest"}</h2><p className="text-sm text-slate-500">{user?.email ?? "Sign in to manage your account"}</p></div></div><div className="mt-5 overflow-hidden rounded-2xl bg-white shadow-sm">{[["My Requests", "requests"], ["My Tickets", "tickets"], ["Parent Tracking", "tracking"], ["Settings", "settings"]].map(([label, target]) => <button key={label} onClick={() => target === "settings" ? window.alert("Settings are available in your dashboard.") : onTab(target === "tickets" ? "profile" : "profile")} className="flex w-full items-center justify-between border-b border-slate-100 p-4 text-left text-sm font-semibold"><span>{label}</span><ChevronRight className="h-4 w-4 text-slate-400" /></button>)}</div>{user ? <button onClick={() => void logout()} className="mt-5 w-full rounded-xl bg-red-50 py-3 text-sm font-bold text-red-600">Log out</button> : <button onClick={() => { window.location.href = "/en/login"; }} className="mt-5 w-full rounded-xl bg-togt-orange py-3 text-sm font-bold text-white">Sign in</button>}<p className="mt-6 text-center text-xs text-slate-400">TOGT Tour &amp; Travel · Version 1.0.0</p></div></main>; }
