import { BadRequestException, ForbiddenException, Injectable, Logger } from '@nestjs/common';
import { Role, User } from '@prisma/client';
import { PrismaService } from '../../prisma/prisma.service';
import { UpdateSiteSettingsDto } from './dto/site-settings.dto';
import { TranslationService } from '../packages/translation.service';

const ALLOWED_KEYS = ['OKRA_LINK', 'OKRA_IMAGE', 'TICKETING_ENABLED', 'ABOUT_VIDEO_URL', 'ABOUT_TEXT'] as const;
export type SiteSettingKey = (typeof ALLOWED_KEYS)[number];

/**
 * Per-locale About-text keys are generated by the OpenRouter translation
 * service when ABOUT_TEXT is saved (never edited directly by admins).
 * publicSettings serves them so the website can switch languages from
 * storage without calling the AI per visitor.
 */
const ABOUT_LOCALE_KEYS = ['ABOUT_TEXT_AR', 'ABOUT_TEXT_AM', 'ABOUT_TEXT_OM'] as const;
const ALL_KEYS = [...ALLOWED_KEYS, ...ABOUT_LOCALE_KEYS];
const DEFAULTS: Record<string, string> = {
  OKRA_LINK: 'https://okratech.et',
  OKRA_IMAGE: '',
  TICKETING_ENABLED: 'true',
  ABOUT_VIDEO_URL: '',
  ABOUT_TEXT: '',
  ABOUT_TEXT_AR: '',
  ABOUT_TEXT_AM: '',
  ABOUT_TEXT_OM: '',
};

const PUBLIC_KEYS = ALL_KEYS;

@Injectable()
export class SiteSettingsService {
  private readonly logger = new Logger(SiteSettingsService.name);
  constructor(private readonly prisma: PrismaService, private readonly translations: TranslationService) {}

  /** Public read: no auth required (used by the website footer/home page). */
  async publicSettings() {
    const rows = await this.prisma.siteSetting.findMany({ where: { key: { in: PUBLIC_KEYS } } });
    const map = new Map(rows.map((row) => [row.key, row.value]));
    return Object.fromEntries(PUBLIC_KEYS.map((key) => [key, map.get(key) ?? DEFAULTS[key]])) as Record<string, string>;
  }

  /** Admin/TECH full read including updater metadata. */
  async listSettings(actor: User) {
    if (actor.role !== Role.ADMIN && actor.role !== Role.TECH) throw new ForbiddenException('Admin access required');
    const rows = await this.prisma.siteSetting.findMany({ where: { key: { in: [...ALLOWED_KEYS] } } });
    const map = new Map(rows.map((row) => [row.key, row]));
    return ALLOWED_KEYS.map((key) => ({
      key,
      value: map.get(key)?.value ?? DEFAULTS[key],
      updatedAt: map.get(key)?.updatedAt ?? null,
      updatedBy: map.get(key)?.updatedById ?? null,
    }));
  }

  async updateSettings(dto: UpdateSiteSettingsDto, actor: User) {
    if (actor.role !== Role.ADMIN && actor.role !== Role.TECH) throw new ForbiddenException('Admin access required');
    const unknown = dto.settings.filter((item) => !(ALLOWED_KEYS as readonly string[]).includes(item.key));
    if (unknown.length) throw new BadRequestException(`Unknown setting keys: ${unknown.map((item) => item.key).join(', ')}`);
    for (const item of dto.settings) {
      if (item.key === 'TICKETING_ENABLED' && !['true', 'false'].includes(item.value)) {
        throw new BadRequestException('TICKETING_ENABLED must be "true" or "false"');
      }
      await this.prisma.siteSetting.upsert({
        where: { key: item.key },
        create: { key: item.key, value: item.value, updatedById: actor.id },
        update: { value: item.value, updatedById: actor.id },
      });
      // Every save of ABOUT_TEXT re-translates into Arabic, Amharic and
      // Afaan Oromoo in the background (fire-and-forget — the save returns
      // immediately; translations land in storage a few seconds later).
      if (item.key === 'ABOUT_TEXT' && item.value.trim()) {
        const text = item.value;
        void this.translations
          .translateText(text)
          .then(async (result) => {
            for (const [locale, value] of Object.entries(result)) {
              const key = `ABOUT_TEXT_${locale.toUpperCase()}`;
              await this.prisma.siteSetting.upsert({
                where: { key },
                create: { key, value, updatedById: actor.id },
                update: { value, updatedById: actor.id },
              });
            }
            this.logger.log(`About text translated into ${Object.keys(result).join(', ')}`);
          })
          .catch((error: Error) => this.logger.warn(`About text translation failed: ${error.message}`));
      }
    }
    this.logger.log(`Site settings updated by ${actor.email}: ${dto.settings.map((item) => item.key).join(', ')}`);
    return this.publicSettings();
  }
}
